;;; ghostel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-ghostel.el

(autoload 'evil-ghostel-mode "evil-ghostel" "\
Minor mode for evil integration in ghostel terminal buffers.

Synchronizes the terminal cursor with Emacs point during evil
state transitions.

This is a minor mode.  If called interactively, toggle the `Evil-Ghostel
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `evil-ghostel-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "evil-ghostel" '("evil-ghostel-"))


;;; Generated autoloads from ghostel.el

(autoload 'ghostel "ghostel" "\
Start a new Ghostel terminal.  If the buffer already exists, switch to it.
With a non-numeric prefix arg, create a new buffer.
With a numeric prefix ARG, switch to the buffer with that number or
create it if it doesn't exist yet.
The name of the buffer is determined by the value of `ghostel-buffer-name'.

(fn &optional ARG)" t)
(autoload 'ghostel-project "ghostel" "\
Start a new Ghostel terminal in the current project's root.
The buffer name is prefixed with the project name.
If a buffer already exists for this project, switch to it.
Otherwise create a new Ghostel buffer.  ARG is passed through to
`ghostel' and accepts the same universal argument conventions.
To add this to `project-switch-commands':
  (add-to-list \\='project-switch-commands \\='(ghostel-project \"Ghostel\") t)

(fn &optional ARG)" t)
(register-definition-prefixes "ghostel" '("ghostel-"))


;;; Generated autoloads from ghostel-compile.el

(autoload 'ghostel-compile "ghostel-compile" "\
Run COMMAND in a ghostel terminal with compilation integration.

Like \\[compile], but uses a ghostel buffer so programs that require
a real TTY work correctly.  The buffer gets a compilation-mode-like
header and footer, and when the command finishes the major mode is
switched to `ghostel-compile-finished-major-mode' (by default
`ghostel-compile-view-mode', derived from `compilation-mode').
Error locations become available through `next-error'.

COMMAND is passed verbatim to `shell-file-name -c', so multi-line
scripts work exactly as in \\[shell-command].  No shell-integration
setup is required — the process sentinel reports the real exit
status.

Output always scrolls as it arrives (equivalent to
`compilation-scroll-output' being non-nil).  `compilation-ask-about-save'
and `compilation-auto-jump-to-first-error' are honoured.  The command
default and history are shared with \\[compile] via `compile-command'
and `compile-history'.

(fn COMMAND)" t)
(defvar ghostel-compile-global-mode nil "\
Non-nil if Ghostel-Compile-Global mode is enabled.
See the `ghostel-compile-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `ghostel-compile-global-mode'.")
(custom-autoload 'ghostel-compile-global-mode "ghostel-compile" nil)
(autoload 'ghostel-compile-global-mode "ghostel-compile" "\
Global minor mode: route all `compile'-style calls through ghostel.

When enabled, advises `compilation-start' so that \\[compile],
\\[recompile], \\[project-compile], and every other caller that
goes through `compilation-start' runs in a ghostel terminal —
giving you a real TTY for progress bars, colours, and curses tools
without having to switch commands.

Modes in `ghostel-compile-global-mode-excluded-modes' (by default,
`grep-mode') still use the stock implementation, since their output
parsers and window-management conventions don't fit a live TTY.

This is a global minor mode.  If called interactively, toggle the
`Ghostel-Compile-Global mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='ghostel-compile-global-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "ghostel-compile" '("ghostel-"))


;;; Generated autoloads from ghostel-debug.el

(autoload 'ghostel-debug-start "ghostel-debug" "\
Start logging ghostel events to *ghostel-debug* buffer.
Logs filter calls, key sends, resize events, redraw decisions
(including DEC 2026 skip/force), and `window-start' anchoring." t)
(autoload 'ghostel-debug-info "ghostel-debug" "\
Display diagnostic info about the ghostel environment.
Collects Emacs version, system info, native module state, terminal
state, and settings into *ghostel-debug* for pasting into bug reports." t)
(register-definition-prefixes "ghostel-debug" '("ghostel-"))


;;; Generated autoloads from ghostel-eshell.el

(autoload 'eshell/ghostel "ghostel-eshell" "\
Run ARGS as a visual command in a dedicated ghostel buffer.
This is an eshell built-in; type `ghostel PROGRAM ...' at the
eshell prompt to launch any program in a ghostel terminal buffer
without adding it to `eshell-visual-commands'.  Dispatches through
`eshell-exec-visual', so when `ghostel-eshell-visual-command-mode'
is enabled the program runs under ghostel; otherwise it falls
back to eshell's default `term-mode' visual handling.

(fn &rest ARGS)")
(defvar ghostel-eshell-visual-command-mode nil "\
Non-nil if Ghostel-Eshell-Visual-Command mode is enabled.
See the `ghostel-eshell-visual-command-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `ghostel-eshell-visual-command-mode'.")
(custom-autoload 'ghostel-eshell-visual-command-mode "ghostel-eshell" nil)
(autoload 'ghostel-eshell-visual-command-mode "ghostel-eshell" "\
Run Eshell visual commands (vim, htop, less, ...) in ghostel buffers.

When enabled, `eshell-exec-visual' is overridden to launch the
program in a dedicated ghostel terminal buffer.  When the program
exits, the buffer stays on `[Process exited]' so any remaining
output is visible; press `q' to dismiss it.  Set
`eshell-destroy-buffer-when-process-dies' to non-nil to kill the
buffer automatically on exit instead.

This is a global minor mode.  If called interactively, toggle the
`Ghostel-Eshell-Visual-Command mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='ghostel-eshell-visual-command-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "ghostel-eshell" '("ghostel-eshell-"))

;;; End of scraped data

(provide 'ghostel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ghostel-autoloads.el ends here
